env:
  global:
  - TERM=dumb
language: java
jdk:
- oraclejdk8
- openjdk8
install: true
script:
- bash mvnw
- bash gradlew

- export root=$(pwd)

# master-SNAPSHOT
- export sample=jitpackmaster
- cd $root/samples/$sample
- bash gradlew #--refresh-dependencies
- bash build/install/$sample/bin/$sample
- bash ./build/install/$sample/bin/$sample trololo

# bintray 0.0.1; JitPack 0.0.1
- >
  for sample in \
    bintray001 \
    jitpack001 \
  ; do
    export sample=bintray001
    cd $root/samples/$sample
    bash gradlew #--refresh-dependencies
    bash build/install/$sample/bin/$sample
    bash ./build/install/$sample/bin/$sample trololo
    bash ./build/install/$sample/bin/$sample $sample
  done
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
