env:
  global:
  - TERM=dumb
language: java
jdk:
- oraclejdk8
- openjdk8
install: true
script:
- bash mvnw
- bash gradlew

- export root=$(pwd)

# master-SNAPSHOT
- export sample=jitpackmaster
- cd $root/samples/$sample
- bash gradlew #--refresh-dependencies
- bash build/install/$sample/bin/$sample
- bash ./build/install/$sample/bin/$sample trololo

# bintray 0.0.1; JitPack 0.0.1
- >
  for sample in \
    bintray001 \
    jitpack001 \
  ; do
    export sample=bintray001
    cd $root/samples/$sample
    bash gradlew #--refresh-dependencies
    bash build/install/$sample/bin/$sample
    bash ./build/install/$sample/bin/$sample trololo
    bash ./build/install/$sample/bin/$sample $sample
  done
cache:
  directories:
  - $HOME/.m2/wrapper
  - $HOME/.m2/repository/ch
  - $HOME/.m2/repository/javax
  - $HOME/.m2/repository/junit
  - $HOME/.m2/repository/org
  - $HOME/.m2/repository/codehaus
  - $HOME/.m2/repository/apache
  - $HOME/.m2/repository/jdom
  - $HOME/.m2/repository/ow2
  - $HOME/.m2/repository/plugins
  - $HOME/.m2/repository/vavr
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/**/ch/junit
  - $HOME/.gradle/**/javax/junit
  - $HOME/.gradle/**/junit/junit
  - $HOME/.gradle/**/org/**
  - $HOME/.gradle/**/codehaus/**
  - $HOME/.gradle/**/apache/**
  - $HOME/.gradle/**/jdom/**
  - $HOME/.gradle/**/ow2/**
  - $HOME/.gradle/**/plugins/**
  - $HOME/.gradle/**/vavr/**
