env:
  global:
  - TERM=dumb
language: java
jdk:
- oraclejdk8
- openjdk8
install: true
script:
- bash mvnw
- bash gradlew
- export root=$(pwd)
# 1.5
- cd $root/samples/jitpack15
#- bash gradlew --refresh-dependencies
- bash gradlew
- bash build/install/jitpack15/bin/jitpack15
- bash ./build/install/jitpack15/bin/jitpack15 trololo
