env:
  global:
  - TERM=dumb
language: java
jdk:
- oraclejdk8
- openjdk8
install: true
script:
- bash mvnw
- bash gradlew
- export root=$(pwd)
- cd $root/samples/java-jitpack
- bash gradlew --refresh-dependencies
