env:
  global:
  - TERM=dumb
language: java
jdk:
- oraclejdk8
- openjdk8
install: true
script:
- bash mvnw
- bash gradlew
- export root=$(pwd)
# master-SNAPSHOT
- export sample=jitpackmaster
- cd $root/samples/$sample
- bash gradlew --refresh-dependencies
- bash build/install/$sample/bin/$sample
- bash ./build/install/$sample/bin/$sample trololo
# 1.5
- export sample=jitpack15
- cd $root/samples/$sample
#- bash gradlew --refresh-dependencies
- bash gradlew
- bash build/install/$sample/bin/$sample
- bash ./build/install/$sample/bin/$sample trololo
